stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - vm-runner
  script:
    - cd /home/student/HFXAIR/group01
    - git fetch origin main
    - git reset --hard origin/main
    - sudo systemctl restart hfxair.service
    - echo "Deployment complete!"
  only:
    - Test-ci/cd-pipeline
