/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/guest-flight`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/arrivals` | `/arrivals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/departures` | `/departures`; params?: Router.UnknownInputParams; } | { pathname: `/components/FlightHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotificationCenter`; params?: Router.UnknownInputParams; } | { pathname: `/components/PushNotificationBanner`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFlightNotifications`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFlightRefresh`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/guest-flight`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/arrivals` | `/arrivals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/departures` | `/departures`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FlightHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NotificationCenter`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PushNotificationBanner`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useFlightNotifications`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useFlightRefresh`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/guest-flight${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/arrivals${`?${string}` | `#${string}` | ''}` | `/arrivals${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/departures${`?${string}` | `#${string}` | ''}` | `/departures${`?${string}` | `#${string}` | ''}` | `/components/FlightHeader${`?${string}` | `#${string}` | ''}` | `/components/NotificationCenter${`?${string}` | `#${string}` | ''}` | `/components/PushNotificationBanner${`?${string}` | `#${string}` | ''}` | `/hooks/useFlightNotifications${`?${string}` | `#${string}` | ''}` | `/hooks/useFlightRefresh${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/guest-flight`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/arrivals` | `/arrivals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/departures` | `/departures`; params?: Router.UnknownInputParams; } | { pathname: `/components/FlightHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotificationCenter`; params?: Router.UnknownInputParams; } | { pathname: `/components/PushNotificationBanner`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFlightNotifications`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFlightRefresh`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
